"""
CSV-Based Knob Space Loader
============================

This module loads KnobSpace from preprocessed CSV files, eliminating
the need for hardcoded knob definitions.

The CSV files are generated by preprocess_knobs.py which merges:
1. Runtime data from pg_settings
2. Tuning metadata (ranges, scales, tiers)

This approach provides:
- No manual knob definition
- Automatic updates when PostgreSQL changes
- Easy addition of new knobs
- Separation of data retrieval from optimization logic
"""

from __future__ import annotations
import ast
from pathlib import Path
from typing import Dict, Any, List, Optional
import pandas as pd

from src.tuner.config.knob_space import (
    KnobSpace,
    KnobDefinition,
    KnobType,
    KnobScale,
)
from src.utils.logger import get_logger, get_color_context

LOGGER = get_logger("KnobLoader")
COLORS = get_color_context()


def csv_type_to_knob_type(vartype: str) -> KnobType:
    """Convert PostgreSQL vartype to KnobType enum"""
    mapping = {
        "integer": KnobType.INTEGER,
        "real": KnobType.REAL,
        "bool": KnobType.BOOLEAN,
        "string": KnobType.ENUM,  # Treat strings as categorical
        "enum": KnobType.ENUM,
    }
    return mapping.get(vartype, KnobType.ENUM)


def csv_scale_to_knob_scale(scale: str) -> KnobScale:
    """Convert scale string to KnobScale enum"""
    mapping = {
        "linear": KnobScale.LINEAR,
        "log": KnobScale.LOG,
        "categorical": KnobScale.CATEGORICAL,
    }
    return mapping.get(scale, KnobScale.LINEAR)


def parse_enumvals(enumvals_str: Any) -> Optional[List[str]]:
    """Parse enumvals from CSV string"""
    if pd.isna(enumvals_str) or enumvals_str == "":
        return None

    if isinstance(enumvals_str, list):
        return [str(value) for value in enumvals_str]

    if isinstance(enumvals_str, str):
        try:
            parsed = ast.literal_eval(enumvals_str)
        except (ValueError, SyntaxError):
            parsed = None

        if isinstance(parsed, list):
            return [str(value) for value in parsed]

        if enumvals_str.startswith("{") and enumvals_str.endswith("}"):
            clean = enumvals_str[1:-1]
            return [
                value.strip().strip("\"'")
                for value in clean.split(",")
                if value.strip()
            ]

        return [enumvals_str]

    return None


def _parse_numeric_bound(raw_value: Any, knob_type: KnobType) -> Optional[float | int]:
    """Parse a numeric bound from CSV data if present."""
    if pd.isna(raw_value):
        return None

    if knob_type == KnobType.REAL:
        return float(raw_value)
    return int(float(raw_value))


def _resolve_numeric_bounds(
    row: pd.Series, knob_type: KnobType
) -> tuple[Optional[float | int], Optional[float | int]]:
    """Resolve effective numeric bounds by intersecting curated and native limits."""
    native_min = _parse_numeric_bound(row.get("min_val"), knob_type)
    native_max = _parse_numeric_bound(row.get("max_val"), knob_type)
    tuning_min = _parse_numeric_bound(row.get("tuning_min"), knob_type)
    tuning_max = _parse_numeric_bound(row.get("tuning_max"), knob_type)

    min_candidates = [value for value in (native_min, tuning_min) if value is not None]
    max_candidates = [value for value in (native_max, tuning_max) if value is not None]

    min_value = max(min_candidates) if min_candidates else None
    max_value = min(max_candidates) if max_candidates else None

    if min_value is not None and max_value is not None and min_value > max_value:
        min_value = native_min if native_min is not None else tuning_min
        max_value = native_max if native_max is not None else tuning_max

    return min_value, max_value


INTEGER_STEP_OVERRIDES = {
    "commit_timestamp_buffers": 16,
    "multixact_member_buffers": 16,
    "multixact_offset_buffers": 16,
    "notify_buffers": 16,
    "serializable_buffers": 16,
    "subtransaction_buffers": 16,
    "transaction_buffers": 16,
}


def _infer_integer_step(row: pd.Series, knob_type: KnobType) -> Optional[int]:
    """Infer integer step alignment for knobs with discrete valid grids."""
    if knob_type != KnobType.INTEGER:
        return None

    return INTEGER_STEP_OVERRIDES.get(str(row["name"]))


def load_knob_space_from_csv(csv_path: str) -> KnobSpace:
    """
    Load KnobSpace from preprocessed CSV file.

    Parameters
    ----------
    csv_path : str
        Path to preprocessed knob CSV

    Returns
    -------
    KnobSpace
        Knob space loaded from CSV

    Example
    -------
    >>> from src.tuner.config.knob_loader import load_knob_space_from_csv
    >>> knob_space = load_knob_space_from_csv("data/tuner_knobs/minimal_knobs.csv")
    >>> print(f"Loaded {len(knob_space)} knobs")
    """
    df = pd.read_csv(csv_path)

    knob_definitions = []

    for _, row in df.iterrows():
        knob_type = csv_type_to_knob_type(row["vartype"])
        scale = csv_scale_to_knob_scale(row["scale"])

        # Parse min/max values
        min_value = None
        max_value = None

        if knob_type in [KnobType.INTEGER, KnobType.REAL]:
            min_value, max_value = _resolve_numeric_bounds(row, knob_type)

        enumvals = parse_enumvals(row.get("enumvals"))
        integer_step = _infer_integer_step(row, knob_type)

        default = row.get("boot_val") or row.get("value")
        if knob_type == KnobType.INTEGER and default is not None:
            try:
                default = int(default)
            except (ValueError, TypeError):
                default = None
        elif knob_type == KnobType.REAL and default is not None:
            try:
                default = float(default)
            except (ValueError, TypeError):
                default = None
        elif knob_type == KnobType.BOOLEAN and default is not None:
            default = str(default).lower() in ["on", "true", "yes", "1"]

        knob_def = KnobDefinition(
            name=row["name"],
            knob_type=knob_type,
            min_value=min_value,
            max_value=max_value,
            scale=scale,
            default=default,
            unit=row.get("unit") if pd.notna(row.get("unit")) else None,
            enum_values=enumvals,
            step=integer_step,
            description=row.get("description", ""),
            category=row.get("custom_category", "other"),
            restart_required=row.get("requires_restart", False),
            hardware_relative=bool(row.get("hardware_relative", False)),
            resource_type=(
                row.get("resource_type")
                if pd.notna(row.get("resource_type")) and row.get("resource_type") != ""
                else None
            ),
        )

        knob_definitions.append(knob_def)

    return KnobSpace(knob_definitions)


def load_knob_space_for_tier(
    tier: str, data_dir: str = "data/tuner_knobs"
) -> KnobSpace:
    """
    Load KnobSpace for a specific tier.

    Parameters
    ----------
    tier : str
        Tier name: 'minimal', 'core', 'standard', or 'extensive'
    data_dir : str
        Directory containing preprocessed CSVs

    Returns
    -------
    KnobSpace
        Knob space for the tier

    Example
    -------
    >>> from src.tuner.config.knob_loader import load_knob_space_for_tier
    >>> minimal_space = load_knob_space_for_tier('minimal')
    >>> print(f"Minimal space has {len(minimal_space)} knobs")
    """
    tier_lower = tier.lower()
    valid_tiers = ["minimal", "core", "standard", "extensive"]

    if tier_lower not in valid_tiers:
        raise ValueError(f"Unknown tier: {tier}. Must be one of {valid_tiers}")

    csv_path = Path(data_dir) / f"{tier_lower}_knobs.csv"

    if not csv_path.exists():
        raise FileNotFoundError(
            f"Preprocessed knobs not found: {csv_path}\n"
            f"Run preprocessing first:\n"
            f"  python -m src.knobs (includes preprocessing)\n"
            f"Current working directory: {Path.cwd()}"
        )

    return load_knob_space_from_csv(str(csv_path))


# Lazy-loaded knob spaces
_KNOB_SPACES: Dict[str, KnobSpace] = {}


def get_knob_space(tier: str = "minimal", force_reload: bool = False) -> KnobSpace:
    """
    Get or load KnobSpace for a tier (cached).

    Parameters
    ----------
    tier : str
        Tier name
    force_reload : bool
        Force reloading from CSV even if cached

    Returns
    -------
    KnobSpace
        Cached or freshly loaded knob space
    """
    if force_reload or tier not in _KNOB_SPACES:
        _KNOB_SPACES[tier] = load_knob_space_for_tier(tier)

    LOGGER.debug("➤ Loaded %d knobs", len(_KNOB_SPACES[tier]))
    return _KNOB_SPACES[tier]
