"""
CSV-Based Knob Space Loader
============================

This module loads KnobSpace from preprocessed CSV files, eliminating
the need for hardcoded knob definitions.

The CSV files are generated by preprocess_knobs.py which merges:
1. Runtime data from pg_settings
2. Tuning metadata (ranges, scales, tiers)

This approach provides:
- No manual knob definition
- Automatic updates when PostgreSQL changes
- Easy addition of new knobs
- Separation of data retrieval from optimization logic
"""

from pathlib import Path
from typing import Dict, Any, List, Optional
import pandas as pd

from src.tuner.config.knob_space import (
    KnobSpace,
    KnobDefinition,
    KnobType,
    KnobScale,
)


def csv_type_to_knob_type(vartype: str) -> KnobType:
    """Convert PostgreSQL vartype to KnobType enum"""
    mapping = {
        "integer": KnobType.INTEGER,
        "real": KnobType.REAL,
        "bool": KnobType.BOOLEAN,
        "string": KnobType.ENUM,  # Treat strings as categorical
        "enum": KnobType.ENUM,
    }
    return mapping.get(vartype, KnobType.ENUM)


def csv_scale_to_knob_scale(scale: str) -> KnobScale:
    """Convert scale string to KnobScale enum"""
    mapping = {
        "linear": KnobScale.LINEAR,
        "log": KnobScale.LOG,
        "categorical": KnobScale.CATEGORICAL,
    }
    return mapping.get(scale, KnobScale.LINEAR)


def parse_enumvals(enumvals_str: Any) -> Optional[List[str]]:
    """Parse enumvals from CSV string"""
    if pd.isna(enumvals_str) or enumvals_str == "":
        return None

    if isinstance(enumvals_str, str):
        # Remove braces and split
        clean = enumvals_str.strip("{}")
        return [v.strip() for v in clean.split(",") if v.strip()]

    return None


def load_knob_space_from_csv(csv_path: str) -> KnobSpace:
    """
    Load KnobSpace from preprocessed CSV file.
    
    Parameters
    ----------
    csv_path : str
        Path to preprocessed knob CSV
        
    Returns
    -------
    KnobSpace
        Knob space loaded from CSV
        
    Example
    -------
    >>> from src.tuner.config.knob_loader import load_knob_space_from_csv
    >>> knob_space = load_knob_space_from_csv("data/tuner_knobs/minimal_knobs.csv")
    >>> print(f"Loaded {len(knob_space)} knobs")
    """
    df = pd.read_csv(csv_path)

    knob_definitions = []

    for _, row in df.iterrows():
        knob_type = csv_type_to_knob_type(row["vartype"])
        scale = csv_scale_to_knob_scale(row["scale"])

        # Parse min/max values
        min_value = None
        max_value = None

        if knob_type in [KnobType.INTEGER, KnobType.REAL]:
            if pd.notna(row.get("tuning_min")):
                min_value = row["tuning_min"]
            elif pd.notna(row.get("min_val")):
                min_value = float(row["min_val"]) if knob_type == KnobType.REAL else int(row["min_val"])

            if pd.notna(row.get("tuning_max")):
                max_value = row["tuning_max"]
            elif pd.notna(row.get("max_val")):
                max_value = float(row["max_val"]) if knob_type == KnobType.REAL else int(row["max_val"])

        enumvals = parse_enumvals(row.get("enumvals"))

        default = row.get("boot_val") or row.get("value")
        if knob_type == KnobType.INTEGER and default is not None:
            try:
                default = int(default)
            except (ValueError, TypeError):
                default = None
        elif knob_type == KnobType.REAL and default is not None:
            try:
                default = float(default)
            except (ValueError, TypeError):
                default = None
        elif knob_type == KnobType.BOOLEAN and default is not None:
            default = str(default).lower() in ["on", "true", "yes", "1"]

        knob_def = KnobDefinition(
            name=row["name"],
            knob_type=knob_type,
            min_value=min_value,
            max_value=max_value,
            scale=scale,
            default=default,
            unit=row.get("unit") if pd.notna(row.get("unit")) else None,
            enum_values=enumvals,
            description=row.get("description", ""),
            category=row.get("custom_category", "other"),
            restart_required=row.get("requires_restart", False),
        )

        knob_definitions.append(knob_def)

    return KnobSpace(knob_definitions)


def load_knob_space_for_tier(
    tier: str,
    data_dir: str = "data/tuner_knobs"
) -> KnobSpace:
    """
    Load KnobSpace for a specific tier.
    
    Parameters
    ----------
    tier : str
        Tier name: 'minimal', 'core', 'standard', or 'extensive'
    data_dir : str
        Directory containing preprocessed CSVs
        
    Returns
    -------
    KnobSpace
        Knob space for the tier
        
    Example
    -------
    >>> from src.tuner.config.knob_loader import load_knob_space_for_tier
    >>> minimal_space = load_knob_space_for_tier('minimal')
    >>> print(f"Minimal space has {len(minimal_space)} knobs")
    """
    tier_lower = tier.lower()
    valid_tiers = ["minimal", "core", "standard", "extensive"]

    if tier_lower not in valid_tiers:
        raise ValueError(
            f"Unknown tier: {tier}. Must be one of {valid_tiers}"
        )

    csv_path = Path(data_dir) / f"{tier_lower}_knobs.csv"

    if not csv_path.exists():
        raise FileNotFoundError(
            f"Preprocessed knobs not found: {csv_path}\n"
            f"Run preprocessing first:\n"
            f"  python -m src.knobs (includes preprocessing)\n"
            f"Current working directory: {Path.cwd()}"
        )

    return load_knob_space_from_csv(str(csv_path))


# Lazy-loaded knob spaces
_KNOB_SPACES: Dict[str, KnobSpace] = {}


def get_knob_space(tier: str = "minimal", force_reload: bool = False) -> KnobSpace:
    """
    Get or load KnobSpace for a tier (cached).
    
    Parameters
    ----------
    tier : str
        Tier name
    force_reload : bool
        Force reloading from CSV even if cached
        
    Returns
    -------
    KnobSpace
        Cached or freshly loaded knob space
    """
    if force_reload or tier not in _KNOB_SPACES:
        _KNOB_SPACES[tier] = load_knob_space_for_tier(tier)

    return _KNOB_SPACES[tier]
