"""
Loader for evaluation comparison JSON reports.
"""

import json
from dataclasses import dataclass
from pathlib import Path

from src.evaluation.types import StatSummary
from src.utils.logger import get_logger
from src.visualization.exceptions import DataLoadError, InvalidSchemaError

LOGGER = get_logger("ComparisonLoader")


@dataclass
class ComparisonData:
    """Parsed evaluation comparison data."""

    metric_names: list[str]
    default_summaries: dict[str, StatSummary]
    tuned_summaries: dict[str, StatSummary]
    improvements: dict[str, float]  # % improvement per metric
    confidence_intervals: dict[str, tuple[float, float]]
    p_values: dict[str, float]
    effect_sizes: dict[str, float]  # Cohen's d
    significant: dict[str, bool]


def _dict_to_statsummary(data: dict) -> StatSummary:
    """Helper to convert JSON dict to StatSummary."""
    return StatSummary(
        mean=data.get("mean", 0.0),
        std=data.get("std", 0.0),
        median=data.get("median", 0.0),
        iqr_lower=data.get("iqr_lower", 0.0),
        iqr_upper=data.get("iqr_upper", 0.0),
        values=data.get("values", []),
    )


def load_comparison(path: Path | str) -> ComparisonData:
    """
    Load a comparison JSON report generated by src.evaluation.
    """
    path = Path(path)
    if not path.exists():
        raise DataLoadError(f"Comparison report not found: {path}")

    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        raise DataLoadError(f"Failed to parse JSON in {path}: {e}") from e

    if "statistics" not in data or "metrics" not in data["statistics"]:
        raise InvalidSchemaError(f"Invalid comparison report format: {path}")

    metrics_list = data["statistics"]["metrics"]

    metric_names = []
    default_summaries = {}
    tuned_summaries = {}
    improvements = {}
    confidence_intervals = {}
    p_values = {}
    effect_sizes = {}
    significant = {}

    for mc in metrics_list:
        name = mc["metric_name"]
        metric_names.append(name)

        default_summaries[name] = _dict_to_statsummary(mc["default"])
        tuned_summaries[name] = _dict_to_statsummary(mc["tuned"])

        improvements[name] = mc.get("improvement_pct", 0.0)

        ci = mc.get("improvement_ci", [0.0, 0.0])
        confidence_intervals[name] = (ci[0], ci[1])

        p_values[name] = mc.get("p_value_corrected", mc.get("p_value", 1.0))
        effect_sizes[name] = mc.get("cohens_d", 0.0)
        significant[name] = mc.get("significant", False)

    return ComparisonData(
        metric_names=metric_names,
        default_summaries=default_summaries,
        tuned_summaries=tuned_summaries,
        improvements=improvements,
        confidence_intervals=confidence_intervals,
        p_values=p_values,
        effect_sizes=effect_sizes,
        significant=significant,
    )


@dataclass
class MultiArmComparisonData:
    """Parsed multi-arm evaluation comparison data."""

    arm_names: list[str]
    summaries_by_arm: dict[str, dict[str, StatSummary]]
    pairwise_statistics: dict[str, ComparisonData]


def load_multi_arm_comparison(path: Path | str) -> MultiArmComparisonData:
    """
    Load a multi-arm comparison JSON report generated by ``run_multi_arm()``.
    """
    path = Path(path)
    if not path.exists():
        raise DataLoadError(f"Multi-arm comparison report not found: {path}")

    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        raise DataLoadError(f"Failed to parse JSON in {path}: {e}") from e

    if "runs_by_arm" not in data:
        raise InvalidSchemaError(
            f"Missing 'runs_by_arm' in multi-arm report: {path}"
        )
    if "pairwise_statistics" not in data:
        raise InvalidSchemaError(
            f"Missing 'pairwise_statistics' in multi-arm report: {path}"
        )

    arm_names = sorted(data["runs_by_arm"].keys())
    summaries_by_arm: dict[str, dict[str, StatSummary]] = {}

    for arm_name, runs in data["runs_by_arm"].items():
        metric_summaries: dict[str, StatSummary] = {}
        if not runs:
            summaries_by_arm[arm_name] = metric_summaries
            continue

        score_vals = [r["score"] for r in runs]
        metric_summaries["score"] = _vals_to_statsummary(score_vals)

        metric_keys = [
            ("latency_p95", "metrics", "latency_p95"),
            ("latency_p99", "metrics", "latency_p99"),
            ("throughput", "metrics", "throughput"),
            ("memory_utilization", "metrics", "memory_utilization"),
        ]
        for display_name, parent_key, field_key in metric_keys:
            vals = [r.get(parent_key, {}).get(field_key, 0.0) for r in runs]
            metric_summaries[display_name] = _vals_to_statsummary(vals)

        summaries_by_arm[arm_name] = metric_summaries

    pairwise: dict[str, ComparisonData] = {}
    for pair_key, pw_data in data["pairwise_statistics"].items():
        stats_section = pw_data.get("statistics", {})
        metrics_list = stats_section.get("metrics", [])

        metric_names = []
        default_summaries: dict[str, StatSummary] = {}
        tuned_summaries: dict[str, StatSummary] = {}
        improvements: dict[str, float] = {}
        confidence_intervals: dict[str, tuple[float, float]] = {}
        p_values: dict[str, float] = {}
        effect_sizes: dict[str, float] = {}
        significant: dict[str, bool] = {}

        for mc in metrics_list:
            name = mc["metric_name"]
            metric_names.append(name)
            default_summaries[name] = _dict_to_statsummary(mc["default"])
            tuned_summaries[name] = _dict_to_statsummary(mc["tuned"])
            improvements[name] = mc.get("improvement_pct", 0.0)
            ci = mc.get("improvement_ci", [0.0, 0.0])
            confidence_intervals[name] = (ci[0], ci[1])
            p_values[name] = mc.get("p_value_corrected", mc.get("p_value", 1.0))
            effect_sizes[name] = mc.get("cohens_d", 0.0)
            significant[name] = mc.get("significant", False)

        pairwise[pair_key] = ComparisonData(
            metric_names=metric_names,
            default_summaries=default_summaries,
            tuned_summaries=tuned_summaries,
            improvements=improvements,
            confidence_intervals=confidence_intervals,
            p_values=p_values,
            effect_sizes=effect_sizes,
            significant=significant,
        )

    return MultiArmComparisonData(
        arm_names=arm_names,
        summaries_by_arm=summaries_by_arm,
        pairwise_statistics=pairwise,
    )


def _vals_to_statsummary(values: list[float]) -> StatSummary:
    """Compute a StatSummary from a list of raw values."""
    import numpy as np

    if not values:
        return StatSummary(
            mean=0.0, std=0.0, median=0.0, iqr_lower=0.0, iqr_upper=0.0, values=[]
        )
    arr = np.array(values, dtype=float)
    return StatSummary(
        mean=float(np.mean(arr)),
        std=float(np.std(arr, ddof=1)) if len(arr) > 1 else 0.0,
        median=float(np.median(arr)),
        iqr_lower=float(np.percentile(arr, 25)),
        iqr_upper=float(np.percentile(arr, 75)),
        values=list(values),
    )
