"""
Loader for evaluation comparison JSON reports.
"""

import json
from dataclasses import dataclass
from pathlib import Path

from src.evaluation.types import StatSummary
from src.utils.logger import get_logger
from src.visualization.exceptions import DataLoadError, InvalidSchemaError

LOGGER = get_logger("ComparisonLoader")


@dataclass
class ComparisonData:
    """Parsed evaluation comparison data."""

    metric_names: list[str]
    default_summaries: dict[str, StatSummary]
    tuned_summaries: dict[str, StatSummary]
    improvements: dict[str, float]  # % improvement per metric
    confidence_intervals: dict[str, tuple[float, float]]
    p_values: dict[str, float]
    effect_sizes: dict[str, float]  # Cohen's d
    significant: dict[str, bool]


def _dict_to_statsummary(data: dict) -> StatSummary:
    """Helper to convert JSON dict to StatSummary."""
    return StatSummary(
        mean=data.get("mean", 0.0),
        std=data.get("std", 0.0),
        median=data.get("median", 0.0),
        iqr_lower=data.get("iqr_lower", 0.0),
        iqr_upper=data.get("iqr_upper", 0.0),
        values=data.get("values", []),
    )


def load_comparison(path: Path | str) -> ComparisonData:
    """
    Load a comparison JSON report generated by src.evaluation.
    """
    path = Path(path)
    if not path.exists():
        raise DataLoadError(f"Comparison report not found: {path}")

    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        raise DataLoadError(f"Failed to parse JSON in {path}: {e}") from e

    if "statistics" not in data or "metrics" not in data["statistics"]:
        raise InvalidSchemaError(f"Invalid comparison report format: {path}")

    metrics_list = data["statistics"]["metrics"]

    metric_names = []
    default_summaries = {}
    tuned_summaries = {}
    improvements = {}
    confidence_intervals = {}
    p_values = {}
    effect_sizes = {}
    significant = {}

    for mc in metrics_list:
        name = mc["metric_name"]
        metric_names.append(name)

        default_summaries[name] = _dict_to_statsummary(mc["default"])
        tuned_summaries[name] = _dict_to_statsummary(mc["tuned"])

        improvements[name] = mc.get("improvement_pct", 0.0)

        ci = mc.get("improvement_ci", [0.0, 0.0])
        confidence_intervals[name] = (ci[0], ci[1])

        p_values[name] = mc.get("p_value_corrected", mc.get("p_value", 1.0))
        effect_sizes[name] = mc.get("cohens_d", 0.0)
        significant[name] = mc.get("significant", False)

    return ComparisonData(
        metric_names=metric_names,
        default_summaries=default_summaries,
        tuned_summaries=tuned_summaries,
        improvements=improvements,
        confidence_intervals=confidence_intervals,
        p_values=p_values,
        effect_sizes=effect_sizes,
        significant=significant,
    )
